enhance logging messages

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -59,42 +59,54 @@ runs:
     - name: Setup kaggle.json
       shell: bash
       run: |
-        echo "Creating the Kaggle configuration directory at ~/.kaggle..."
+        log_message() {
+            echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
+        }
+        log_message "Creating the Kaggle configuration directory at ~/.kaggle..."
         mkdir -p ~/.kaggle
         
-        echo "Writing credentials to kaggle.json..."
+        log_message "Writing credentials to kaggle.json..."
+        
+        if [ -z "${{ inputs.username }}" ]; then
+            echo "::error::Username is required but was empty"
+            exit 1
+        fi
+        
+        if [ -z "${{ inputs.key }}" ]; then
+            echo "::error::Kaggle key is required but was empty"
+            exit 1
+        fi
+        
         echo "{\"username\":\"${{ inputs.username }}\",\"key\":\"${{ inputs.key }}\"}" > ~/.kaggle/kaggle.json
         
-        echo "Setting appropriate permissions for kaggle.json (read and write for user only)..."
+        log_message "Setting appropriate permissions for kaggle.json (read and write for user only)..."
         chmod 600 ~/.kaggle/kaggle.json
         
-        echo "Kaggle configuration setup complete."
+        log_message "Kaggle configuration setup complete."
 
     - name: Set up Notebook Kernel
       shell: bash
       run: |
-        echo "Setting up the notebook for Kaggle execution..."
+        log_message() {
+            echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
+        }
         
-        # Define the output notebook and retrieve repository information
+        log_message "Setting up the notebook for Kaggle execution..."
+        
         action_path=$(realpath "${{ github.action_path }}")
-        OUTPUT_NOTEBOOK="$action_path/project_setup.ipynb"
-        echo "Notebook will be saved as: $OUTPUT_NOTEBOOK"
+        OUTPUT_NOTEBOOK="$action_path/script.ipynb"
+        log_message "Notebook will be saved as: $OUTPUT_NOTEBOOK"
         
-        REPO_URL=$(git config --get remote.origin.url)
-        echo "Repository URL: $REPO_URL"
-        
+        REPO_URL=$(git config --get remote.origin.url)        
         REPO_NAME=$(basename "$REPO_URL" .git)
-        
         BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
-        echo "Current branch: $BRANCH_NAME"
+        log_message "Will clone Repository URL: $REPO_URL Current branch: $BRANCH_NAME"
         
         CUSTOM_SCRIPT="${{ inputs.custom_script }}"
-        echo "Custom script to be included in the notebook: $CUSTOM_SCRIPT"
+        log_message "Custom script to be included in the notebook: $CUSTOM_SCRIPT"
         
-        # Define the command for installing dependencies within the cloned directory
         dependencies="!cd /kaggle/working/$REPO_NAME && pip install -r requirements.txt"
         
-        # Create the Jupyter notebook JSON structure with three cells
         cat <<EOM > "$OUTPUT_NOTEBOOK"
         {
           "cells": [
@@ -142,31 +154,32 @@ runs:
         }
         EOM
         
-        echo "Notebook '$OUTPUT_NOTEBOOK' created successfully"
+        log_message "Notebook '$OUTPUT_NOTEBOOK' created successfully"
 
 
     - name: Setup test
       shell: bash
       run: |
+        log_message() {
+            echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
+        }
         action_path=$(realpath "${{ github.action_path }}")
         OUTPUT_NOTEBOOK="$action_path/project_setup.ipynb"
         
-        echo "Navigating to the action path: '$action_path'"
+        log_message "Navigating to the action path: '$action_path'"
         cd "$action_path"
         
-        echo "Initializing Kaggle kernel metadata at path: '$action_path'"
+        log_message "Initializing Kaggle kernel metadata at path: '$action_path'"
         kaggle kernels init -p "$action_path"
         
         json_path="$action_path/kernel-metadata.json"
-        echo "Kernel metadata template created at: $json_path"
+        log_message "Kernel metadata template created at: $json_path"
         
-        echo "Loading current metadata for processing..."
         metadata=$(jq -r '. | tojson' < "$json_path")
         
         title="${{ inputs.title }}"  
         formatted_title=$(echo "$title" | tr '[:upper:]' '[:lower:]' | sed 's/ /_/g')
         
-        echo "Updating metadata with specified inputs..."
         metadata=$(echo "$metadata" | jq --arg title "${{ inputs.title }}" \
                                          --arg code_file "$OUTPUT_NOTEBOOK" \
                                          --arg enable_gpu "${{ inputs.enable_gpu }}" \
@@ -180,16 +193,16 @@ runs:
                                            .enable_gpu = true |
                                            .enable_internet = true')
         
-        echo "Saving updated metadata back to $json_path"
-        echo "$metadata" | jq '.' > "$json_path"
+        log_message "Saving updated metadata back to $json_path"
+        log_message "$metadata" | jq '.' > "$json_path"
         
-        echo "Final kernel metadata content:"
+        log_message "Final kernel metadata content:"
         cat "$json_path"  
         
-        echo "Pushing Kaggle kernel with updated metadata..."
+        log_message "Pushing Kaggle kernel with updated metadata..."
         kaggle kernels push -p "$action_path"
         
-        echo "Kaggle kernel setup and push completed successfully."
+        log_message "Kaggle kernel setup and push completed successfully."
     
 
     - name: Check status
